export const GHOST_DECIMALS = 18;
export const WEI_PER_GHOST = 10n ** 18n;
export const TOTAL_SUPPLY_WEI = 33_000_000n * WEI_PER_GHOST;
export const AIRDROP_ALLOC_WEI = 6_600_000n * WEI_PER_GHOST;
export const ONE_HUNDRED_GHOST_WEI = 100n * WEI_PER_GHOST;
export const WELCOME_CAMPAIGN_MAX_BUDGET_WEI = (AIRDROP_ALLOC_WEI * 500n) / 10_000n;
export const WELCOME_CAMPAIGN_MAX_ACCOUNTS_100 = WELCOME_CAMPAIGN_MAX_BUDGET_WEI / ONE_HUNDRED_GHOST_WEI;
